name: compliance_companion_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  amplify_auth_cognito: ^2.3.0
  amplify_authenticator: ^2.1.1
  amplify_flutter: ^2.3.0
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
