// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsLcB0TJ5pKgSZzRH4FK2w4A0IikappT0',
    appId: '1:739431043561:android:7ec1c352f5043bef78fb78',
    messagingSenderId: '739431043561',
    projectId: 'flutter-task-manager-df8b1',
    storageBucket: 'flutter-task-manager-df8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4zm75KMrVrqNK5qHz_ywXCi-OWEZSU4',
    appId: '1:739431043561:ios:f425449cf6c1d39878fb78',
    messagingSenderId: '739431043561',
    projectId: 'flutter-task-manager-df8b1',
    storageBucket: 'flutter-task-manager-df8b1.appspot.com',
    iosClientId: '739431043561-b70ikrvirpqeq24dgpr1hqeaf5ljgetq.apps.googleusercontent.com',
    iosBundleId: 'com.example.complianceCompanionApp',
  );

}